#import "../theme.typ": page

#show: page.with(
  route: "blog/structure-in-typst/index.html",
  title: "Putting the site structure in Typst",
  date: "2026-02-10",
  tags: ("typost", "typst", "ssg"),
  description: "Why the entry file is a Typst program.",
  url: "/blog/structure-in-typst/",
  section: "blog",
)

= Putting the site structure in Typst

This site is generated by *typost*, a static site generator that treats
Typst as its authoring language. There is no content convention and no
special syntax: each page is a Typst file, and the entry includes them.

#outline(title: [On this page], depth: 2)

== Why Typst?

Because Typst already has what a site needs:

+ markup for prose,
+ functions for reuse,
+ loops and arrays for collections,
+ math, tables, and code out of the box.

== A code block

```rust
fn main() {
    println!("hello from typost");
}
```

== Inline code and links

The page directive is `page.with(route: ...)`. You can link to the
#link("/about/")[about page] or the #link("/blog/")[blog index].

== Math

Typesetting is Typst's specialty:

$ integral_0^infinity e^(-x^2) dif x = sqrt(pi) / 2 $

== A table

#table(
  columns: 3,
  align: (left, center, center),
  [*Feature*], [*Typst*], [*Markdown*],
  [Math], [yes], [partial],
  [Functions], [yes], [no],
  [Layout], [yes], [no],
)

== Quotes and footnotes

#quote(block: true)[
  Typst is a new markup-based typesetting system that is designed to be
  as powerful as LaTeX while being much easier to learn and use.
]

Term lists work too:#footnote[One of Typst's many built-in elements.]

/ Static site generator: a tool that emits a site ahead of time.
/ Bundle target: Typst's multi-document output.
