[package]
name = "typost-plugin-spoiler"
description = "Hover-to-reveal spoiler plugin for typost."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
typost-core = { path = "../typost-core" }
anyhow.workspace = true
